project_id = "akhrktpddxaizspnikgb"

[functions.trm-screen]
verify_jwt = false

[functions.moralis-screen]
verify_jwt = false

[functions.skyflow-tokenize]
verify_jwt = false

[functions.skyflow-detokenize]
verify_jwt = false

[functions.screen-with-privacy]
verify_jwt = false